package objects

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/dscsystems/go-dnp3"
)

// TestGeneratedFilesAreCommitted is a cheap guard against editing generated
// code by hand: every generated file must carry the DO NOT EDIT banner, so a
// reviewer and a grep both know where the change belongs.
func TestGeneratedFilesAreCommitted(t *testing.T) {
	matches, err := filepath.Glob("zz_generated_*.go")
	if err != nil {
		t.Fatal(err)
	}
	if len(matches) < 2 {
		t.Fatalf("found %d generated files, want the descriptors and the codecs", len(matches))
	}
	for _, path := range matches {
		data, err := os.ReadFile(path)
		if err != nil {
			t.Fatal(err)
		}
		if !strings.HasPrefix(string(data), "// Code generated by internal/gen") {
			t.Errorf("%s is missing the generated-code banner", path)
		}
		if !strings.Contains(string(data), "DO NOT EDIT") {
			t.Errorf("%s is missing the DO NOT EDIT marker", path)
		}
	}
}

// TestSpecCoversEveryLevelOneAndTwoGroup checks the registry against the
// groups a Level 2 device must implement. A missing group here is a
// conformance gap that would otherwise only surface against real hardware.
func TestSpecCoversEveryLevelOneAndTwoGroup(t *testing.T) {
	required := []struct {
		gv   GroupVar
		what string
	}{
		{GV(1, 1), "binary input, packed"},
		{GV(1, 2), "binary input with flags"},
		{GV(2, 1), "binary input event"},
		{GV(2, 2), "binary input event with time"},
		{GV(10, 2), "binary output status"},
		{GV(12, 1), "control relay output block"},
		{GV(20, 1), "counter"},
		{GV(21, 1), "frozen counter"},
		{GV(22, 1), "counter event"},
		{GV(30, 1), "analog input"},
		{GV(30, 3), "analog input without flags"},
		{GV(32, 1), "analog input event"},
		{GV(40, 1), "analog output status"},
		{GV(41, 1), "analog output command"},
		{GV(50, 1), "time and date"},
		{GV(51, 1), "common time of occurrence"},
		{GV(52, 2), "time delay, fine"},
		{GV(60, 1), "class 0 data"},
		{GV(60, 2), "class 1 data"},
		{GV(60, 3), "class 2 data"},
		{GV(60, 4), "class 3 data"},
		{GV(80, 1), "internal indications"},
	}
	for _, r := range required {
		if _, ok := Lookup(r.gv); !ok {
			t.Errorf("%s (%s) is missing from the registry", r.gv, r.what)
		}
	}
}

// TestDescriptorSizesMatchTheStandard pins sizes that were derived by hand
// from the field layouts. The generator computes these by summing field
// widths, so a wrong field width in the spec shows up here rather than against
// a device.
func TestDescriptorSizesMatchTheStandard(t *testing.T) {
	tests := []struct {
		gv     GroupVar
		octets int
	}{
		{GV(1, 2), 1},   // flags
		{GV(2, 2), 7},   // flags + 48-bit time
		{GV(2, 3), 3},   // flags + 16-bit relative time
		{GV(12, 1), 11}, // CROB
		{GV(20, 1), 5},  // flags + 32-bit
		{GV(20, 2), 3},  // flags + 16-bit
		{GV(21, 5), 11}, // flags + 32-bit + time
		{GV(30, 1), 5},  // flags + 32-bit
		{GV(30, 2), 3},  // flags + 16-bit
		{GV(30, 3), 4},  // 32-bit, no flags
		{GV(30, 5), 5},  // flags + single
		{GV(30, 6), 9},  // flags + double
		{GV(32, 3), 11}, // flags + 32-bit + time
		{GV(32, 8), 15}, // flags + double + time
		{GV(41, 1), 5},  // 32-bit + status
		{GV(41, 4), 9},  // double + status
		{GV(50, 1), 6},  // 48-bit time
		{GV(51, 1), 6},  // CTO
		{GV(52, 1), 2},  // coarse delay
	}
	for _, tc := range tests {
		d, ok := Lookup(tc.gv)
		if !ok {
			t.Errorf("%s missing from the registry", tc.gv)
			continue
		}
		got, ok := d.SizeOctets()
		if !ok {
			t.Errorf("%s has no whole-octet size", tc.gv)
			continue
		}
		if got != tc.octets {
			t.Errorf("%s (%s) = %d octets, want %d", tc.gv, d.Name, got, tc.octets)
		}
	}
}

// TestFloatVariationsAreMarked pins the descriptor metadata that a variation
// number alone cannot tell you: variation 3 is a 32-bit integer in group 30
// and a single-precision float in group 40.
func TestFloatVariationsAreMarked(t *testing.T) {
	tests := []struct {
		gv    GroupVar
		float bool
		bits  int
	}{
		{GV(30, 1), false, 32},
		{GV(30, 3), false, 32},
		{GV(30, 5), true, 32},
		{GV(30, 6), true, 64},
		{GV(40, 1), false, 32},
		{GV(40, 3), true, 32}, // the one that breaks the naive rule
		{GV(40, 4), true, 64},
		{GV(42, 5), true, 32},
	}
	for _, tc := range tests {
		d, ok := Lookup(tc.gv)
		if !ok {
			t.Fatalf("%s missing", tc.gv)
		}
		if d.FloatValue != tc.float {
			t.Errorf("%s (%s): FloatValue = %v, want %v", tc.gv, d.Name, d.FloatValue, tc.float)
		}
		if d.ValueBits != tc.bits {
			t.Errorf("%s (%s): ValueBits = %d, want %d", tc.gv, d.Name, d.ValueBits, tc.bits)
		}
	}
}

func TestKindsAreAssigned(t *testing.T) {
	tests := []struct {
		gv   GroupVar
		kind Kind
	}{
		{GV(1, 2), KindStatic},
		{GV(2, 1), KindEvent},
		{GV(12, 1), KindCommand},
		{GV(41, 1), KindCommand},
		{GV(50, 1), KindTime},
		{GV(60, 1), KindClass},
		{GV(80, 1), KindIndication},
		{GV(34, 1), KindDeadband},
	}
	for _, tc := range tests {
		d, _ := Lookup(tc.gv)
		if d.Kind != tc.kind {
			t.Errorf("%s (%s): kind = %v, want %v", tc.gv, d.Name, d.Kind, tc.kind)
		}
	}
}

func TestMeasurementTypesAreAssigned(t *testing.T) {
	tests := []struct {
		gv GroupVar
		pt dnp3.PointType
	}{
		{GV(1, 2), dnp3.TypeBinary},
		{GV(3, 2), dnp3.TypeDoubleBitBinary},
		{GV(20, 1), dnp3.TypeCounter},
		{GV(21, 1), dnp3.TypeFrozenCounter},
		{GV(30, 1), dnp3.TypeAnalog},
		{GV(10, 2), dnp3.TypeBinaryOutputStatus},
		{GV(40, 1), dnp3.TypeAnalogOutputStatus},
		{GV(60, 1), dnp3.TypeUnknown}, // class objects are not measurements
		{GV(12, 1), dnp3.TypeUnknown}, // nor are commands
	}
	for _, tc := range tests {
		d, _ := Lookup(tc.gv)
		if d.Measurement != tc.pt {
			t.Errorf("%s (%s): measurement = %v, want %v", tc.gv, d.Name, d.Measurement, tc.pt)
		}
	}
}
