// Code generated by internal/gen from objects/spec/dnp3_objects.yaml. DO NOT EDIT.

package objects

import (
	"encoding/binary"
	"math"

	"github.com/dscsystems/go-dnp3"
)

var (
	_ = binary.LittleEndian
	_ = math.Float64bits
	_ = dnp3.Online
)

// ---- dnp3.Binary ----

// parseG1V2 decodes g1v2, BinaryInputWithFlags.
func parseG1V2(buf []byte, ctx Context) dnp3.Binary {
	var v dnp3.Binary
	_ = buf[0] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = buf[0]&0x80 != 0
	return v
}

// writeG1V2 encodes g1v2, BinaryInputWithFlags.
func writeG1V2(dst []byte, v dnp3.Binary, ctx Context) []byte {
	_ = ctx
	flags := v.Flags &^ dnp3.StateBit
	if v.Value {
		flags |= dnp3.StateBit
	}
	dst = append(dst, byte(flags))
	return dst
}

// parseG2V1 decodes g2v1, BinaryInputEventNoTime.
func parseG2V1(buf []byte, ctx Context) dnp3.Binary {
	var v dnp3.Binary
	_ = buf[0] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = buf[0]&0x80 != 0
	return v
}

// writeG2V1 encodes g2v1, BinaryInputEventNoTime.
func writeG2V1(dst []byte, v dnp3.Binary, ctx Context) []byte {
	_ = ctx
	flags := v.Flags &^ dnp3.StateBit
	if v.Value {
		flags |= dnp3.StateBit
	}
	dst = append(dst, byte(flags))
	return dst
}

// parseG2V2 decodes g2v2, BinaryInputEventAbsTime.
func parseG2V2(buf []byte, ctx Context) dnp3.Binary {
	var v dnp3.Binary
	_ = buf[6] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = buf[0]&0x80 != 0
	v.Time = dnp3.Timestamp{Time: dnp3.DNP3ToTime(uint64(buf[1])<<0 | uint64(buf[2])<<8 | uint64(buf[3])<<16 | uint64(buf[4])<<24 | uint64(buf[5])<<32 | uint64(buf[6])<<40), Quality: ctx.TimeQuality()}
	return v
}

// writeG2V2 encodes g2v2, BinaryInputEventAbsTime.
func writeG2V2(dst []byte, v dnp3.Binary, ctx Context) []byte {
	_ = ctx
	flags := v.Flags &^ dnp3.StateBit
	if v.Value {
		flags |= dnp3.StateBit
	}
	dst = append(dst, byte(flags))
	dst = appendTime48(dst, dnp3.TimeToDNP3(v.Time.Time))
	return dst
}

// parseG2V3 decodes g2v3, BinaryInputEventRelTime.
func parseG2V3(buf []byte, ctx Context) dnp3.Binary {
	var v dnp3.Binary
	_ = buf[2] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = buf[0]&0x80 != 0
	// A relative-time event is an offset from the common time of
	// occurrence in a preceding group 51 object. Without one the
	// offset is meaningless, so the timestamp is left invalid
	// rather than being anchored to the epoch.
	v.Time = ctx.RelativeTime(uint16(binary.LittleEndian.Uint16(buf[1:3])))
	return v
}

// writeG2V3 encodes g2v3, BinaryInputEventRelTime.
func writeG2V3(dst []byte, v dnp3.Binary, ctx Context) []byte {
	_ = ctx
	flags := v.Flags &^ dnp3.StateBit
	if v.Value {
		flags |= dnp3.StateBit
	}
	dst = append(dst, byte(flags))
	dst = binary.LittleEndian.AppendUint16(dst, ctx.RelativeOffset(v.Time))
	return dst
}

var binaryCodecs = map[GroupVar]Codec[dnp3.Binary]{
	GV(1, 2): {Parse: parseG1V2, Write: writeG1V2},
	GV(2, 1): {Parse: parseG2V1, Write: writeG2V1},
	GV(2, 2): {Parse: parseG2V2, Write: writeG2V2},
	GV(2, 3): {Parse: parseG2V3, Write: writeG2V3},
}

// ---- dnp3.DoubleBitBinary ----

// parseG3V2 decodes g3v2, DoubleBitInputWithFlags.
func parseG3V2(buf []byte, ctx Context) dnp3.DoubleBitBinary {
	var v dnp3.DoubleBitBinary
	_ = buf[0] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = dnp3.DoubleBit(buf[0] >> 6)
	return v
}

// writeG3V2 encodes g3v2, DoubleBitInputWithFlags.
func writeG3V2(dst []byte, v dnp3.DoubleBitBinary, ctx Context) []byte {
	_ = ctx
	dst = append(dst, byte(v.Flags&0x3F)|byte(v.Value&0x03)<<6)
	return dst
}

// parseG4V1 decodes g4v1, DoubleBitEventNoTime.
func parseG4V1(buf []byte, ctx Context) dnp3.DoubleBitBinary {
	var v dnp3.DoubleBitBinary
	_ = buf[0] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = dnp3.DoubleBit(buf[0] >> 6)
	return v
}

// writeG4V1 encodes g4v1, DoubleBitEventNoTime.
func writeG4V1(dst []byte, v dnp3.DoubleBitBinary, ctx Context) []byte {
	_ = ctx
	dst = append(dst, byte(v.Flags&0x3F)|byte(v.Value&0x03)<<6)
	return dst
}

// parseG4V2 decodes g4v2, DoubleBitEventAbsTime.
func parseG4V2(buf []byte, ctx Context) dnp3.DoubleBitBinary {
	var v dnp3.DoubleBitBinary
	_ = buf[6] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = dnp3.DoubleBit(buf[0] >> 6)
	v.Time = dnp3.Timestamp{Time: dnp3.DNP3ToTime(uint64(buf[1])<<0 | uint64(buf[2])<<8 | uint64(buf[3])<<16 | uint64(buf[4])<<24 | uint64(buf[5])<<32 | uint64(buf[6])<<40), Quality: ctx.TimeQuality()}
	return v
}

// writeG4V2 encodes g4v2, DoubleBitEventAbsTime.
func writeG4V2(dst []byte, v dnp3.DoubleBitBinary, ctx Context) []byte {
	_ = ctx
	dst = append(dst, byte(v.Flags&0x3F)|byte(v.Value&0x03)<<6)
	dst = appendTime48(dst, dnp3.TimeToDNP3(v.Time.Time))
	return dst
}

// parseG4V3 decodes g4v3, DoubleBitEventRelTime.
func parseG4V3(buf []byte, ctx Context) dnp3.DoubleBitBinary {
	var v dnp3.DoubleBitBinary
	_ = buf[2] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = dnp3.DoubleBit(buf[0] >> 6)
	// A relative-time event is an offset from the common time of
	// occurrence in a preceding group 51 object. Without one the
	// offset is meaningless, so the timestamp is left invalid
	// rather than being anchored to the epoch.
	v.Time = ctx.RelativeTime(uint16(binary.LittleEndian.Uint16(buf[1:3])))
	return v
}

// writeG4V3 encodes g4v3, DoubleBitEventRelTime.
func writeG4V3(dst []byte, v dnp3.DoubleBitBinary, ctx Context) []byte {
	_ = ctx
	dst = append(dst, byte(v.Flags&0x3F)|byte(v.Value&0x03)<<6)
	dst = binary.LittleEndian.AppendUint16(dst, ctx.RelativeOffset(v.Time))
	return dst
}

var doublebitCodecs = map[GroupVar]Codec[dnp3.DoubleBitBinary]{
	GV(3, 2): {Parse: parseG3V2, Write: writeG3V2},
	GV(4, 1): {Parse: parseG4V1, Write: writeG4V1},
	GV(4, 2): {Parse: parseG4V2, Write: writeG4V2},
	GV(4, 3): {Parse: parseG4V3, Write: writeG4V3},
}

// ---- dnp3.Counter ----

// parseG20V1 decodes g20v1, Counter32WithFlag.
func parseG20V1(buf []byte, ctx Context) dnp3.Counter {
	var v dnp3.Counter
	_ = buf[4] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = binary.LittleEndian.Uint32(buf[1:5])
	return v
}

// writeG20V1 encodes g20v1, Counter32WithFlag.
func writeG20V1(dst []byte, v dnp3.Counter, ctx Context) []byte {
	_ = ctx
	dst = append(dst, byte(v.Flags))
	dst = binary.LittleEndian.AppendUint32(dst, uint32(v.Value))
	return dst
}

// parseG20V2 decodes g20v2, Counter16WithFlag.
func parseG20V2(buf []byte, ctx Context) dnp3.Counter {
	var v dnp3.Counter
	_ = buf[2] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = uint32(binary.LittleEndian.Uint16(buf[1:3]))
	return v
}

// writeG20V2 encodes g20v2, Counter16WithFlag.
func writeG20V2(dst []byte, v dnp3.Counter, ctx Context) []byte {
	_ = ctx
	dst = append(dst, byte(v.Flags))
	dst = binary.LittleEndian.AppendUint16(dst, uint16(v.Value))
	return dst
}

// parseG20V5 decodes g20v5, Counter32NoFlag.
func parseG20V5(buf []byte, ctx Context) dnp3.Counter {
	var v dnp3.Counter
	_ = buf[3] // bounds check once, then index freely
	v.Flags = dnp3.Online
	v.Value = binary.LittleEndian.Uint32(buf[0:4])
	return v
}

// writeG20V5 encodes g20v5, Counter32NoFlag.
func writeG20V5(dst []byte, v dnp3.Counter, ctx Context) []byte {
	_ = ctx
	dst = binary.LittleEndian.AppendUint32(dst, uint32(v.Value))
	return dst
}

// parseG20V6 decodes g20v6, Counter16NoFlag.
func parseG20V6(buf []byte, ctx Context) dnp3.Counter {
	var v dnp3.Counter
	_ = buf[1] // bounds check once, then index freely
	v.Flags = dnp3.Online
	v.Value = uint32(binary.LittleEndian.Uint16(buf[0:2]))
	return v
}

// writeG20V6 encodes g20v6, Counter16NoFlag.
func writeG20V6(dst []byte, v dnp3.Counter, ctx Context) []byte {
	_ = ctx
	dst = binary.LittleEndian.AppendUint16(dst, uint16(v.Value))
	return dst
}

// parseG22V1 decodes g22v1, CounterEvent32WithFlag.
func parseG22V1(buf []byte, ctx Context) dnp3.Counter {
	var v dnp3.Counter
	_ = buf[4] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = binary.LittleEndian.Uint32(buf[1:5])
	return v
}

// writeG22V1 encodes g22v1, CounterEvent32WithFlag.
func writeG22V1(dst []byte, v dnp3.Counter, ctx Context) []byte {
	_ = ctx
	dst = append(dst, byte(v.Flags))
	dst = binary.LittleEndian.AppendUint32(dst, uint32(v.Value))
	return dst
}

// parseG22V2 decodes g22v2, CounterEvent16WithFlag.
func parseG22V2(buf []byte, ctx Context) dnp3.Counter {
	var v dnp3.Counter
	_ = buf[2] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = uint32(binary.LittleEndian.Uint16(buf[1:3]))
	return v
}

// writeG22V2 encodes g22v2, CounterEvent16WithFlag.
func writeG22V2(dst []byte, v dnp3.Counter, ctx Context) []byte {
	_ = ctx
	dst = append(dst, byte(v.Flags))
	dst = binary.LittleEndian.AppendUint16(dst, uint16(v.Value))
	return dst
}

// parseG22V5 decodes g22v5, CounterEvent32WithFlagTime.
func parseG22V5(buf []byte, ctx Context) dnp3.Counter {
	var v dnp3.Counter
	_ = buf[10] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = binary.LittleEndian.Uint32(buf[1:5])
	v.Time = dnp3.Timestamp{Time: dnp3.DNP3ToTime(uint64(buf[5])<<0 | uint64(buf[6])<<8 | uint64(buf[7])<<16 | uint64(buf[8])<<24 | uint64(buf[9])<<32 | uint64(buf[10])<<40), Quality: ctx.TimeQuality()}
	return v
}

// writeG22V5 encodes g22v5, CounterEvent32WithFlagTime.
func writeG22V5(dst []byte, v dnp3.Counter, ctx Context) []byte {
	_ = ctx
	dst = append(dst, byte(v.Flags))
	dst = binary.LittleEndian.AppendUint32(dst, uint32(v.Value))
	dst = appendTime48(dst, dnp3.TimeToDNP3(v.Time.Time))
	return dst
}

// parseG22V6 decodes g22v6, CounterEvent16WithFlagTime.
func parseG22V6(buf []byte, ctx Context) dnp3.Counter {
	var v dnp3.Counter
	_ = buf[8] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = uint32(binary.LittleEndian.Uint16(buf[1:3]))
	v.Time = dnp3.Timestamp{Time: dnp3.DNP3ToTime(uint64(buf[3])<<0 | uint64(buf[4])<<8 | uint64(buf[5])<<16 | uint64(buf[6])<<24 | uint64(buf[7])<<32 | uint64(buf[8])<<40), Quality: ctx.TimeQuality()}
	return v
}

// writeG22V6 encodes g22v6, CounterEvent16WithFlagTime.
func writeG22V6(dst []byte, v dnp3.Counter, ctx Context) []byte {
	_ = ctx
	dst = append(dst, byte(v.Flags))
	dst = binary.LittleEndian.AppendUint16(dst, uint16(v.Value))
	dst = appendTime48(dst, dnp3.TimeToDNP3(v.Time.Time))
	return dst
}

var counterCodecs = map[GroupVar]Codec[dnp3.Counter]{
	GV(20, 1): {Parse: parseG20V1, Write: writeG20V1},
	GV(20, 2): {Parse: parseG20V2, Write: writeG20V2},
	GV(20, 5): {Parse: parseG20V5, Write: writeG20V5},
	GV(20, 6): {Parse: parseG20V6, Write: writeG20V6},
	GV(22, 1): {Parse: parseG22V1, Write: writeG22V1},
	GV(22, 2): {Parse: parseG22V2, Write: writeG22V2},
	GV(22, 5): {Parse: parseG22V5, Write: writeG22V5},
	GV(22, 6): {Parse: parseG22V6, Write: writeG22V6},
}

// ---- dnp3.FrozenCounter ----

// parseG21V1 decodes g21v1, FrozenCounter32WithFlag.
func parseG21V1(buf []byte, ctx Context) dnp3.FrozenCounter {
	var v dnp3.FrozenCounter
	_ = buf[4] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = binary.LittleEndian.Uint32(buf[1:5])
	return v
}

// writeG21V1 encodes g21v1, FrozenCounter32WithFlag.
func writeG21V1(dst []byte, v dnp3.FrozenCounter, ctx Context) []byte {
	_ = ctx
	dst = append(dst, byte(v.Flags))
	dst = binary.LittleEndian.AppendUint32(dst, uint32(v.Value))
	return dst
}

// parseG21V2 decodes g21v2, FrozenCounter16WithFlag.
func parseG21V2(buf []byte, ctx Context) dnp3.FrozenCounter {
	var v dnp3.FrozenCounter
	_ = buf[2] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = uint32(binary.LittleEndian.Uint16(buf[1:3]))
	return v
}

// writeG21V2 encodes g21v2, FrozenCounter16WithFlag.
func writeG21V2(dst []byte, v dnp3.FrozenCounter, ctx Context) []byte {
	_ = ctx
	dst = append(dst, byte(v.Flags))
	dst = binary.LittleEndian.AppendUint16(dst, uint16(v.Value))
	return dst
}

// parseG21V5 decodes g21v5, FrozenCounter32WithFlagTime.
func parseG21V5(buf []byte, ctx Context) dnp3.FrozenCounter {
	var v dnp3.FrozenCounter
	_ = buf[10] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = binary.LittleEndian.Uint32(buf[1:5])
	v.Time = dnp3.Timestamp{Time: dnp3.DNP3ToTime(uint64(buf[5])<<0 | uint64(buf[6])<<8 | uint64(buf[7])<<16 | uint64(buf[8])<<24 | uint64(buf[9])<<32 | uint64(buf[10])<<40), Quality: ctx.TimeQuality()}
	return v
}

// writeG21V5 encodes g21v5, FrozenCounter32WithFlagTime.
func writeG21V5(dst []byte, v dnp3.FrozenCounter, ctx Context) []byte {
	_ = ctx
	dst = append(dst, byte(v.Flags))
	dst = binary.LittleEndian.AppendUint32(dst, uint32(v.Value))
	dst = appendTime48(dst, dnp3.TimeToDNP3(v.Time.Time))
	return dst
}

// parseG21V6 decodes g21v6, FrozenCounter16WithFlagTime.
func parseG21V6(buf []byte, ctx Context) dnp3.FrozenCounter {
	var v dnp3.FrozenCounter
	_ = buf[8] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = uint32(binary.LittleEndian.Uint16(buf[1:3]))
	v.Time = dnp3.Timestamp{Time: dnp3.DNP3ToTime(uint64(buf[3])<<0 | uint64(buf[4])<<8 | uint64(buf[5])<<16 | uint64(buf[6])<<24 | uint64(buf[7])<<32 | uint64(buf[8])<<40), Quality: ctx.TimeQuality()}
	return v
}

// writeG21V6 encodes g21v6, FrozenCounter16WithFlagTime.
func writeG21V6(dst []byte, v dnp3.FrozenCounter, ctx Context) []byte {
	_ = ctx
	dst = append(dst, byte(v.Flags))
	dst = binary.LittleEndian.AppendUint16(dst, uint16(v.Value))
	dst = appendTime48(dst, dnp3.TimeToDNP3(v.Time.Time))
	return dst
}

// parseG21V9 decodes g21v9, FrozenCounter32NoFlag.
func parseG21V9(buf []byte, ctx Context) dnp3.FrozenCounter {
	var v dnp3.FrozenCounter
	_ = buf[3] // bounds check once, then index freely
	v.Flags = dnp3.Online
	v.Value = binary.LittleEndian.Uint32(buf[0:4])
	return v
}

// writeG21V9 encodes g21v9, FrozenCounter32NoFlag.
func writeG21V9(dst []byte, v dnp3.FrozenCounter, ctx Context) []byte {
	_ = ctx
	dst = binary.LittleEndian.AppendUint32(dst, uint32(v.Value))
	return dst
}

// parseG21V10 decodes g21v10, FrozenCounter16NoFlag.
func parseG21V10(buf []byte, ctx Context) dnp3.FrozenCounter {
	var v dnp3.FrozenCounter
	_ = buf[1] // bounds check once, then index freely
	v.Flags = dnp3.Online
	v.Value = uint32(binary.LittleEndian.Uint16(buf[0:2]))
	return v
}

// writeG21V10 encodes g21v10, FrozenCounter16NoFlag.
func writeG21V10(dst []byte, v dnp3.FrozenCounter, ctx Context) []byte {
	_ = ctx
	dst = binary.LittleEndian.AppendUint16(dst, uint16(v.Value))
	return dst
}

// parseG23V1 decodes g23v1, FrozenCounterEvent32WithFlag.
func parseG23V1(buf []byte, ctx Context) dnp3.FrozenCounter {
	var v dnp3.FrozenCounter
	_ = buf[4] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = binary.LittleEndian.Uint32(buf[1:5])
	return v
}

// writeG23V1 encodes g23v1, FrozenCounterEvent32WithFlag.
func writeG23V1(dst []byte, v dnp3.FrozenCounter, ctx Context) []byte {
	_ = ctx
	dst = append(dst, byte(v.Flags))
	dst = binary.LittleEndian.AppendUint32(dst, uint32(v.Value))
	return dst
}

// parseG23V2 decodes g23v2, FrozenCounterEvent16WithFlag.
func parseG23V2(buf []byte, ctx Context) dnp3.FrozenCounter {
	var v dnp3.FrozenCounter
	_ = buf[2] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = uint32(binary.LittleEndian.Uint16(buf[1:3]))
	return v
}

// writeG23V2 encodes g23v2, FrozenCounterEvent16WithFlag.
func writeG23V2(dst []byte, v dnp3.FrozenCounter, ctx Context) []byte {
	_ = ctx
	dst = append(dst, byte(v.Flags))
	dst = binary.LittleEndian.AppendUint16(dst, uint16(v.Value))
	return dst
}

// parseG23V5 decodes g23v5, FrozenCounterEvent32WithFlagTime.
func parseG23V5(buf []byte, ctx Context) dnp3.FrozenCounter {
	var v dnp3.FrozenCounter
	_ = buf[10] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = binary.LittleEndian.Uint32(buf[1:5])
	v.Time = dnp3.Timestamp{Time: dnp3.DNP3ToTime(uint64(buf[5])<<0 | uint64(buf[6])<<8 | uint64(buf[7])<<16 | uint64(buf[8])<<24 | uint64(buf[9])<<32 | uint64(buf[10])<<40), Quality: ctx.TimeQuality()}
	return v
}

// writeG23V5 encodes g23v5, FrozenCounterEvent32WithFlagTime.
func writeG23V5(dst []byte, v dnp3.FrozenCounter, ctx Context) []byte {
	_ = ctx
	dst = append(dst, byte(v.Flags))
	dst = binary.LittleEndian.AppendUint32(dst, uint32(v.Value))
	dst = appendTime48(dst, dnp3.TimeToDNP3(v.Time.Time))
	return dst
}

// parseG23V6 decodes g23v6, FrozenCounterEvent16WithFlagTime.
func parseG23V6(buf []byte, ctx Context) dnp3.FrozenCounter {
	var v dnp3.FrozenCounter
	_ = buf[8] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = uint32(binary.LittleEndian.Uint16(buf[1:3]))
	v.Time = dnp3.Timestamp{Time: dnp3.DNP3ToTime(uint64(buf[3])<<0 | uint64(buf[4])<<8 | uint64(buf[5])<<16 | uint64(buf[6])<<24 | uint64(buf[7])<<32 | uint64(buf[8])<<40), Quality: ctx.TimeQuality()}
	return v
}

// writeG23V6 encodes g23v6, FrozenCounterEvent16WithFlagTime.
func writeG23V6(dst []byte, v dnp3.FrozenCounter, ctx Context) []byte {
	_ = ctx
	dst = append(dst, byte(v.Flags))
	dst = binary.LittleEndian.AppendUint16(dst, uint16(v.Value))
	dst = appendTime48(dst, dnp3.TimeToDNP3(v.Time.Time))
	return dst
}

var frozencounterCodecs = map[GroupVar]Codec[dnp3.FrozenCounter]{
	GV(21, 1):  {Parse: parseG21V1, Write: writeG21V1},
	GV(21, 2):  {Parse: parseG21V2, Write: writeG21V2},
	GV(21, 5):  {Parse: parseG21V5, Write: writeG21V5},
	GV(21, 6):  {Parse: parseG21V6, Write: writeG21V6},
	GV(21, 9):  {Parse: parseG21V9, Write: writeG21V9},
	GV(21, 10): {Parse: parseG21V10, Write: writeG21V10},
	GV(23, 1):  {Parse: parseG23V1, Write: writeG23V1},
	GV(23, 2):  {Parse: parseG23V2, Write: writeG23V2},
	GV(23, 5):  {Parse: parseG23V5, Write: writeG23V5},
	GV(23, 6):  {Parse: parseG23V6, Write: writeG23V6},
}

// ---- dnp3.Analog ----

// parseG30V1 decodes g30v1, AnalogInput32WithFlag.
func parseG30V1(buf []byte, ctx Context) dnp3.Analog {
	var v dnp3.Analog
	_ = buf[4] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = float64(int32(binary.LittleEndian.Uint32(buf[1:5])))
	return v
}

// writeG30V1 encodes g30v1, AnalogInput32WithFlag.
func writeG30V1(dst []byte, v dnp3.Analog, ctx Context) []byte {
	_ = ctx
	dst = append(dst, byte(v.Flags))
	dst = binary.LittleEndian.AppendUint32(dst, uint32(clampInt32(v.Value)))
	return dst
}

// parseG30V2 decodes g30v2, AnalogInput16WithFlag.
func parseG30V2(buf []byte, ctx Context) dnp3.Analog {
	var v dnp3.Analog
	_ = buf[2] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = float64(int16(binary.LittleEndian.Uint16(buf[1:3])))
	return v
}

// writeG30V2 encodes g30v2, AnalogInput16WithFlag.
func writeG30V2(dst []byte, v dnp3.Analog, ctx Context) []byte {
	_ = ctx
	dst = append(dst, byte(v.Flags))
	dst = binary.LittleEndian.AppendUint16(dst, uint16(clampInt16(v.Value)))
	return dst
}

// parseG30V3 decodes g30v3, AnalogInput32NoFlag.
func parseG30V3(buf []byte, ctx Context) dnp3.Analog {
	var v dnp3.Analog
	_ = buf[3] // bounds check once, then index freely
	v.Flags = dnp3.Online
	v.Value = float64(int32(binary.LittleEndian.Uint32(buf[0:4])))
	return v
}

// writeG30V3 encodes g30v3, AnalogInput32NoFlag.
func writeG30V3(dst []byte, v dnp3.Analog, ctx Context) []byte {
	_ = ctx
	dst = binary.LittleEndian.AppendUint32(dst, uint32(clampInt32(v.Value)))
	return dst
}

// parseG30V4 decodes g30v4, AnalogInput16NoFlag.
func parseG30V4(buf []byte, ctx Context) dnp3.Analog {
	var v dnp3.Analog
	_ = buf[1] // bounds check once, then index freely
	v.Flags = dnp3.Online
	v.Value = float64(int16(binary.LittleEndian.Uint16(buf[0:2])))
	return v
}

// writeG30V4 encodes g30v4, AnalogInput16NoFlag.
func writeG30V4(dst []byte, v dnp3.Analog, ctx Context) []byte {
	_ = ctx
	dst = binary.LittleEndian.AppendUint16(dst, uint16(clampInt16(v.Value)))
	return dst
}

// parseG30V5 decodes g30v5, AnalogInputFloatWithFlag.
func parseG30V5(buf []byte, ctx Context) dnp3.Analog {
	var v dnp3.Analog
	_ = buf[4] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = float64(math.Float32frombits(binary.LittleEndian.Uint32(buf[1:5])))
	return v
}

// writeG30V5 encodes g30v5, AnalogInputFloatWithFlag.
func writeG30V5(dst []byte, v dnp3.Analog, ctx Context) []byte {
	_ = ctx
	dst = append(dst, byte(v.Flags))
	dst = binary.LittleEndian.AppendUint32(dst, math.Float32bits(float32(v.Value)))
	return dst
}

// parseG30V6 decodes g30v6, AnalogInputDoubleWithFlag.
func parseG30V6(buf []byte, ctx Context) dnp3.Analog {
	var v dnp3.Analog
	_ = buf[8] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = math.Float64frombits(binary.LittleEndian.Uint64(buf[1:9]))
	return v
}

// writeG30V6 encodes g30v6, AnalogInputDoubleWithFlag.
func writeG30V6(dst []byte, v dnp3.Analog, ctx Context) []byte {
	_ = ctx
	dst = append(dst, byte(v.Flags))
	dst = binary.LittleEndian.AppendUint64(dst, math.Float64bits(v.Value))
	return dst
}

// parseG31V1 decodes g31v1, FrozenAnalog32WithFlag.
func parseG31V1(buf []byte, ctx Context) dnp3.Analog {
	var v dnp3.Analog
	_ = buf[4] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = float64(int32(binary.LittleEndian.Uint32(buf[1:5])))
	return v
}

// writeG31V1 encodes g31v1, FrozenAnalog32WithFlag.
func writeG31V1(dst []byte, v dnp3.Analog, ctx Context) []byte {
	_ = ctx
	dst = append(dst, byte(v.Flags))
	dst = binary.LittleEndian.AppendUint32(dst, uint32(clampInt32(v.Value)))
	return dst
}

// parseG31V2 decodes g31v2, FrozenAnalog16WithFlag.
func parseG31V2(buf []byte, ctx Context) dnp3.Analog {
	var v dnp3.Analog
	_ = buf[2] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = float64(int16(binary.LittleEndian.Uint16(buf[1:3])))
	return v
}

// writeG31V2 encodes g31v2, FrozenAnalog16WithFlag.
func writeG31V2(dst []byte, v dnp3.Analog, ctx Context) []byte {
	_ = ctx
	dst = append(dst, byte(v.Flags))
	dst = binary.LittleEndian.AppendUint16(dst, uint16(clampInt16(v.Value)))
	return dst
}

// parseG31V3 decodes g31v3, FrozenAnalog32WithFlagTime.
func parseG31V3(buf []byte, ctx Context) dnp3.Analog {
	var v dnp3.Analog
	_ = buf[10] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = float64(int32(binary.LittleEndian.Uint32(buf[1:5])))
	v.Time = dnp3.Timestamp{Time: dnp3.DNP3ToTime(uint64(buf[5])<<0 | uint64(buf[6])<<8 | uint64(buf[7])<<16 | uint64(buf[8])<<24 | uint64(buf[9])<<32 | uint64(buf[10])<<40), Quality: ctx.TimeQuality()}
	return v
}

// writeG31V3 encodes g31v3, FrozenAnalog32WithFlagTime.
func writeG31V3(dst []byte, v dnp3.Analog, ctx Context) []byte {
	_ = ctx
	dst = append(dst, byte(v.Flags))
	dst = binary.LittleEndian.AppendUint32(dst, uint32(clampInt32(v.Value)))
	dst = appendTime48(dst, dnp3.TimeToDNP3(v.Time.Time))
	return dst
}

// parseG31V4 decodes g31v4, FrozenAnalog16WithFlagTime.
func parseG31V4(buf []byte, ctx Context) dnp3.Analog {
	var v dnp3.Analog
	_ = buf[8] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = float64(int16(binary.LittleEndian.Uint16(buf[1:3])))
	v.Time = dnp3.Timestamp{Time: dnp3.DNP3ToTime(uint64(buf[3])<<0 | uint64(buf[4])<<8 | uint64(buf[5])<<16 | uint64(buf[6])<<24 | uint64(buf[7])<<32 | uint64(buf[8])<<40), Quality: ctx.TimeQuality()}
	return v
}

// writeG31V4 encodes g31v4, FrozenAnalog16WithFlagTime.
func writeG31V4(dst []byte, v dnp3.Analog, ctx Context) []byte {
	_ = ctx
	dst = append(dst, byte(v.Flags))
	dst = binary.LittleEndian.AppendUint16(dst, uint16(clampInt16(v.Value)))
	dst = appendTime48(dst, dnp3.TimeToDNP3(v.Time.Time))
	return dst
}

// parseG31V5 decodes g31v5, FrozenAnalog32NoFlag.
func parseG31V5(buf []byte, ctx Context) dnp3.Analog {
	var v dnp3.Analog
	_ = buf[3] // bounds check once, then index freely
	v.Flags = dnp3.Online
	v.Value = float64(int32(binary.LittleEndian.Uint32(buf[0:4])))
	return v
}

// writeG31V5 encodes g31v5, FrozenAnalog32NoFlag.
func writeG31V5(dst []byte, v dnp3.Analog, ctx Context) []byte {
	_ = ctx
	dst = binary.LittleEndian.AppendUint32(dst, uint32(clampInt32(v.Value)))
	return dst
}

// parseG31V6 decodes g31v6, FrozenAnalog16NoFlag.
func parseG31V6(buf []byte, ctx Context) dnp3.Analog {
	var v dnp3.Analog
	_ = buf[1] // bounds check once, then index freely
	v.Flags = dnp3.Online
	v.Value = float64(int16(binary.LittleEndian.Uint16(buf[0:2])))
	return v
}

// writeG31V6 encodes g31v6, FrozenAnalog16NoFlag.
func writeG31V6(dst []byte, v dnp3.Analog, ctx Context) []byte {
	_ = ctx
	dst = binary.LittleEndian.AppendUint16(dst, uint16(clampInt16(v.Value)))
	return dst
}

// parseG31V7 decodes g31v7, FrozenAnalogFloatWithFlag.
func parseG31V7(buf []byte, ctx Context) dnp3.Analog {
	var v dnp3.Analog
	_ = buf[4] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = float64(math.Float32frombits(binary.LittleEndian.Uint32(buf[1:5])))
	return v
}

// writeG31V7 encodes g31v7, FrozenAnalogFloatWithFlag.
func writeG31V7(dst []byte, v dnp3.Analog, ctx Context) []byte {
	_ = ctx
	dst = append(dst, byte(v.Flags))
	dst = binary.LittleEndian.AppendUint32(dst, math.Float32bits(float32(v.Value)))
	return dst
}

// parseG31V8 decodes g31v8, FrozenAnalogDoubleWithFlag.
func parseG31V8(buf []byte, ctx Context) dnp3.Analog {
	var v dnp3.Analog
	_ = buf[8] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = math.Float64frombits(binary.LittleEndian.Uint64(buf[1:9]))
	return v
}

// writeG31V8 encodes g31v8, FrozenAnalogDoubleWithFlag.
func writeG31V8(dst []byte, v dnp3.Analog, ctx Context) []byte {
	_ = ctx
	dst = append(dst, byte(v.Flags))
	dst = binary.LittleEndian.AppendUint64(dst, math.Float64bits(v.Value))
	return dst
}

// parseG32V1 decodes g32v1, AnalogEvent32WithFlag.
func parseG32V1(buf []byte, ctx Context) dnp3.Analog {
	var v dnp3.Analog
	_ = buf[4] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = float64(int32(binary.LittleEndian.Uint32(buf[1:5])))
	return v
}

// writeG32V1 encodes g32v1, AnalogEvent32WithFlag.
func writeG32V1(dst []byte, v dnp3.Analog, ctx Context) []byte {
	_ = ctx
	dst = append(dst, byte(v.Flags))
	dst = binary.LittleEndian.AppendUint32(dst, uint32(clampInt32(v.Value)))
	return dst
}

// parseG32V2 decodes g32v2, AnalogEvent16WithFlag.
func parseG32V2(buf []byte, ctx Context) dnp3.Analog {
	var v dnp3.Analog
	_ = buf[2] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = float64(int16(binary.LittleEndian.Uint16(buf[1:3])))
	return v
}

// writeG32V2 encodes g32v2, AnalogEvent16WithFlag.
func writeG32V2(dst []byte, v dnp3.Analog, ctx Context) []byte {
	_ = ctx
	dst = append(dst, byte(v.Flags))
	dst = binary.LittleEndian.AppendUint16(dst, uint16(clampInt16(v.Value)))
	return dst
}

// parseG32V3 decodes g32v3, AnalogEvent32WithFlagTime.
func parseG32V3(buf []byte, ctx Context) dnp3.Analog {
	var v dnp3.Analog
	_ = buf[10] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = float64(int32(binary.LittleEndian.Uint32(buf[1:5])))
	v.Time = dnp3.Timestamp{Time: dnp3.DNP3ToTime(uint64(buf[5])<<0 | uint64(buf[6])<<8 | uint64(buf[7])<<16 | uint64(buf[8])<<24 | uint64(buf[9])<<32 | uint64(buf[10])<<40), Quality: ctx.TimeQuality()}
	return v
}

// writeG32V3 encodes g32v3, AnalogEvent32WithFlagTime.
func writeG32V3(dst []byte, v dnp3.Analog, ctx Context) []byte {
	_ = ctx
	dst = append(dst, byte(v.Flags))
	dst = binary.LittleEndian.AppendUint32(dst, uint32(clampInt32(v.Value)))
	dst = appendTime48(dst, dnp3.TimeToDNP3(v.Time.Time))
	return dst
}

// parseG32V4 decodes g32v4, AnalogEvent16WithFlagTime.
func parseG32V4(buf []byte, ctx Context) dnp3.Analog {
	var v dnp3.Analog
	_ = buf[8] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = float64(int16(binary.LittleEndian.Uint16(buf[1:3])))
	v.Time = dnp3.Timestamp{Time: dnp3.DNP3ToTime(uint64(buf[3])<<0 | uint64(buf[4])<<8 | uint64(buf[5])<<16 | uint64(buf[6])<<24 | uint64(buf[7])<<32 | uint64(buf[8])<<40), Quality: ctx.TimeQuality()}
	return v
}

// writeG32V4 encodes g32v4, AnalogEvent16WithFlagTime.
func writeG32V4(dst []byte, v dnp3.Analog, ctx Context) []byte {
	_ = ctx
	dst = append(dst, byte(v.Flags))
	dst = binary.LittleEndian.AppendUint16(dst, uint16(clampInt16(v.Value)))
	dst = appendTime48(dst, dnp3.TimeToDNP3(v.Time.Time))
	return dst
}

// parseG32V5 decodes g32v5, AnalogEventFloatWithFlag.
func parseG32V5(buf []byte, ctx Context) dnp3.Analog {
	var v dnp3.Analog
	_ = buf[4] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = float64(math.Float32frombits(binary.LittleEndian.Uint32(buf[1:5])))
	return v
}

// writeG32V5 encodes g32v5, AnalogEventFloatWithFlag.
func writeG32V5(dst []byte, v dnp3.Analog, ctx Context) []byte {
	_ = ctx
	dst = append(dst, byte(v.Flags))
	dst = binary.LittleEndian.AppendUint32(dst, math.Float32bits(float32(v.Value)))
	return dst
}

// parseG32V6 decodes g32v6, AnalogEventDoubleWithFlag.
func parseG32V6(buf []byte, ctx Context) dnp3.Analog {
	var v dnp3.Analog
	_ = buf[8] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = math.Float64frombits(binary.LittleEndian.Uint64(buf[1:9]))
	return v
}

// writeG32V6 encodes g32v6, AnalogEventDoubleWithFlag.
func writeG32V6(dst []byte, v dnp3.Analog, ctx Context) []byte {
	_ = ctx
	dst = append(dst, byte(v.Flags))
	dst = binary.LittleEndian.AppendUint64(dst, math.Float64bits(v.Value))
	return dst
}

// parseG32V7 decodes g32v7, AnalogEventFloatWithFlagTime.
func parseG32V7(buf []byte, ctx Context) dnp3.Analog {
	var v dnp3.Analog
	_ = buf[10] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = float64(math.Float32frombits(binary.LittleEndian.Uint32(buf[1:5])))
	v.Time = dnp3.Timestamp{Time: dnp3.DNP3ToTime(uint64(buf[5])<<0 | uint64(buf[6])<<8 | uint64(buf[7])<<16 | uint64(buf[8])<<24 | uint64(buf[9])<<32 | uint64(buf[10])<<40), Quality: ctx.TimeQuality()}
	return v
}

// writeG32V7 encodes g32v7, AnalogEventFloatWithFlagTime.
func writeG32V7(dst []byte, v dnp3.Analog, ctx Context) []byte {
	_ = ctx
	dst = append(dst, byte(v.Flags))
	dst = binary.LittleEndian.AppendUint32(dst, math.Float32bits(float32(v.Value)))
	dst = appendTime48(dst, dnp3.TimeToDNP3(v.Time.Time))
	return dst
}

// parseG32V8 decodes g32v8, AnalogEventDoubleWithFlagTime.
func parseG32V8(buf []byte, ctx Context) dnp3.Analog {
	var v dnp3.Analog
	_ = buf[14] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = math.Float64frombits(binary.LittleEndian.Uint64(buf[1:9]))
	v.Time = dnp3.Timestamp{Time: dnp3.DNP3ToTime(uint64(buf[9])<<0 | uint64(buf[10])<<8 | uint64(buf[11])<<16 | uint64(buf[12])<<24 | uint64(buf[13])<<32 | uint64(buf[14])<<40), Quality: ctx.TimeQuality()}
	return v
}

// writeG32V8 encodes g32v8, AnalogEventDoubleWithFlagTime.
func writeG32V8(dst []byte, v dnp3.Analog, ctx Context) []byte {
	_ = ctx
	dst = append(dst, byte(v.Flags))
	dst = binary.LittleEndian.AppendUint64(dst, math.Float64bits(v.Value))
	dst = appendTime48(dst, dnp3.TimeToDNP3(v.Time.Time))
	return dst
}

// parseG33V1 decodes g33v1, FrozenAnalogEvent32WithFlag.
func parseG33V1(buf []byte, ctx Context) dnp3.Analog {
	var v dnp3.Analog
	_ = buf[4] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = float64(int32(binary.LittleEndian.Uint32(buf[1:5])))
	return v
}

// writeG33V1 encodes g33v1, FrozenAnalogEvent32WithFlag.
func writeG33V1(dst []byte, v dnp3.Analog, ctx Context) []byte {
	_ = ctx
	dst = append(dst, byte(v.Flags))
	dst = binary.LittleEndian.AppendUint32(dst, uint32(clampInt32(v.Value)))
	return dst
}

// parseG33V2 decodes g33v2, FrozenAnalogEvent16WithFlag.
func parseG33V2(buf []byte, ctx Context) dnp3.Analog {
	var v dnp3.Analog
	_ = buf[2] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = float64(int16(binary.LittleEndian.Uint16(buf[1:3])))
	return v
}

// writeG33V2 encodes g33v2, FrozenAnalogEvent16WithFlag.
func writeG33V2(dst []byte, v dnp3.Analog, ctx Context) []byte {
	_ = ctx
	dst = append(dst, byte(v.Flags))
	dst = binary.LittleEndian.AppendUint16(dst, uint16(clampInt16(v.Value)))
	return dst
}

// parseG33V3 decodes g33v3, FrozenAnalogEvent32WithFlagTime.
func parseG33V3(buf []byte, ctx Context) dnp3.Analog {
	var v dnp3.Analog
	_ = buf[10] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = float64(int32(binary.LittleEndian.Uint32(buf[1:5])))
	v.Time = dnp3.Timestamp{Time: dnp3.DNP3ToTime(uint64(buf[5])<<0 | uint64(buf[6])<<8 | uint64(buf[7])<<16 | uint64(buf[8])<<24 | uint64(buf[9])<<32 | uint64(buf[10])<<40), Quality: ctx.TimeQuality()}
	return v
}

// writeG33V3 encodes g33v3, FrozenAnalogEvent32WithFlagTime.
func writeG33V3(dst []byte, v dnp3.Analog, ctx Context) []byte {
	_ = ctx
	dst = append(dst, byte(v.Flags))
	dst = binary.LittleEndian.AppendUint32(dst, uint32(clampInt32(v.Value)))
	dst = appendTime48(dst, dnp3.TimeToDNP3(v.Time.Time))
	return dst
}

// parseG33V4 decodes g33v4, FrozenAnalogEvent16WithFlagTime.
func parseG33V4(buf []byte, ctx Context) dnp3.Analog {
	var v dnp3.Analog
	_ = buf[8] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = float64(int16(binary.LittleEndian.Uint16(buf[1:3])))
	v.Time = dnp3.Timestamp{Time: dnp3.DNP3ToTime(uint64(buf[3])<<0 | uint64(buf[4])<<8 | uint64(buf[5])<<16 | uint64(buf[6])<<24 | uint64(buf[7])<<32 | uint64(buf[8])<<40), Quality: ctx.TimeQuality()}
	return v
}

// writeG33V4 encodes g33v4, FrozenAnalogEvent16WithFlagTime.
func writeG33V4(dst []byte, v dnp3.Analog, ctx Context) []byte {
	_ = ctx
	dst = append(dst, byte(v.Flags))
	dst = binary.LittleEndian.AppendUint16(dst, uint16(clampInt16(v.Value)))
	dst = appendTime48(dst, dnp3.TimeToDNP3(v.Time.Time))
	return dst
}

// parseG33V5 decodes g33v5, FrozenAnalogEventFloatWithFlag.
func parseG33V5(buf []byte, ctx Context) dnp3.Analog {
	var v dnp3.Analog
	_ = buf[4] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = float64(math.Float32frombits(binary.LittleEndian.Uint32(buf[1:5])))
	return v
}

// writeG33V5 encodes g33v5, FrozenAnalogEventFloatWithFlag.
func writeG33V5(dst []byte, v dnp3.Analog, ctx Context) []byte {
	_ = ctx
	dst = append(dst, byte(v.Flags))
	dst = binary.LittleEndian.AppendUint32(dst, math.Float32bits(float32(v.Value)))
	return dst
}

// parseG33V6 decodes g33v6, FrozenAnalogEventDoubleWithFlag.
func parseG33V6(buf []byte, ctx Context) dnp3.Analog {
	var v dnp3.Analog
	_ = buf[8] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = math.Float64frombits(binary.LittleEndian.Uint64(buf[1:9]))
	return v
}

// writeG33V6 encodes g33v6, FrozenAnalogEventDoubleWithFlag.
func writeG33V6(dst []byte, v dnp3.Analog, ctx Context) []byte {
	_ = ctx
	dst = append(dst, byte(v.Flags))
	dst = binary.LittleEndian.AppendUint64(dst, math.Float64bits(v.Value))
	return dst
}

// parseG33V7 decodes g33v7, FrozenAnalogEventFloatWithFlagTime.
func parseG33V7(buf []byte, ctx Context) dnp3.Analog {
	var v dnp3.Analog
	_ = buf[10] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = float64(math.Float32frombits(binary.LittleEndian.Uint32(buf[1:5])))
	v.Time = dnp3.Timestamp{Time: dnp3.DNP3ToTime(uint64(buf[5])<<0 | uint64(buf[6])<<8 | uint64(buf[7])<<16 | uint64(buf[8])<<24 | uint64(buf[9])<<32 | uint64(buf[10])<<40), Quality: ctx.TimeQuality()}
	return v
}

// writeG33V7 encodes g33v7, FrozenAnalogEventFloatWithFlagTime.
func writeG33V7(dst []byte, v dnp3.Analog, ctx Context) []byte {
	_ = ctx
	dst = append(dst, byte(v.Flags))
	dst = binary.LittleEndian.AppendUint32(dst, math.Float32bits(float32(v.Value)))
	dst = appendTime48(dst, dnp3.TimeToDNP3(v.Time.Time))
	return dst
}

// parseG33V8 decodes g33v8, FrozenAnalogEventDoubleWithFlagTime.
func parseG33V8(buf []byte, ctx Context) dnp3.Analog {
	var v dnp3.Analog
	_ = buf[14] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = math.Float64frombits(binary.LittleEndian.Uint64(buf[1:9]))
	v.Time = dnp3.Timestamp{Time: dnp3.DNP3ToTime(uint64(buf[9])<<0 | uint64(buf[10])<<8 | uint64(buf[11])<<16 | uint64(buf[12])<<24 | uint64(buf[13])<<32 | uint64(buf[14])<<40), Quality: ctx.TimeQuality()}
	return v
}

// writeG33V8 encodes g33v8, FrozenAnalogEventDoubleWithFlagTime.
func writeG33V8(dst []byte, v dnp3.Analog, ctx Context) []byte {
	_ = ctx
	dst = append(dst, byte(v.Flags))
	dst = binary.LittleEndian.AppendUint64(dst, math.Float64bits(v.Value))
	dst = appendTime48(dst, dnp3.TimeToDNP3(v.Time.Time))
	return dst
}

var analogCodecs = map[GroupVar]Codec[dnp3.Analog]{
	GV(30, 1): {Parse: parseG30V1, Write: writeG30V1},
	GV(30, 2): {Parse: parseG30V2, Write: writeG30V2},
	GV(30, 3): {Parse: parseG30V3, Write: writeG30V3},
	GV(30, 4): {Parse: parseG30V4, Write: writeG30V4},
	GV(30, 5): {Parse: parseG30V5, Write: writeG30V5},
	GV(30, 6): {Parse: parseG30V6, Write: writeG30V6},
	GV(31, 1): {Parse: parseG31V1, Write: writeG31V1},
	GV(31, 2): {Parse: parseG31V2, Write: writeG31V2},
	GV(31, 3): {Parse: parseG31V3, Write: writeG31V3},
	GV(31, 4): {Parse: parseG31V4, Write: writeG31V4},
	GV(31, 5): {Parse: parseG31V5, Write: writeG31V5},
	GV(31, 6): {Parse: parseG31V6, Write: writeG31V6},
	GV(31, 7): {Parse: parseG31V7, Write: writeG31V7},
	GV(31, 8): {Parse: parseG31V8, Write: writeG31V8},
	GV(32, 1): {Parse: parseG32V1, Write: writeG32V1},
	GV(32, 2): {Parse: parseG32V2, Write: writeG32V2},
	GV(32, 3): {Parse: parseG32V3, Write: writeG32V3},
	GV(32, 4): {Parse: parseG32V4, Write: writeG32V4},
	GV(32, 5): {Parse: parseG32V5, Write: writeG32V5},
	GV(32, 6): {Parse: parseG32V6, Write: writeG32V6},
	GV(32, 7): {Parse: parseG32V7, Write: writeG32V7},
	GV(32, 8): {Parse: parseG32V8, Write: writeG32V8},
	GV(33, 1): {Parse: parseG33V1, Write: writeG33V1},
	GV(33, 2): {Parse: parseG33V2, Write: writeG33V2},
	GV(33, 3): {Parse: parseG33V3, Write: writeG33V3},
	GV(33, 4): {Parse: parseG33V4, Write: writeG33V4},
	GV(33, 5): {Parse: parseG33V5, Write: writeG33V5},
	GV(33, 6): {Parse: parseG33V6, Write: writeG33V6},
	GV(33, 7): {Parse: parseG33V7, Write: writeG33V7},
	GV(33, 8): {Parse: parseG33V8, Write: writeG33V8},
}

// ---- dnp3.BinaryOutputStatus ----

// parseG10V2 decodes g10v2, BinaryOutputWithFlags.
func parseG10V2(buf []byte, ctx Context) dnp3.BinaryOutputStatus {
	var v dnp3.BinaryOutputStatus
	_ = buf[0] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = buf[0]&0x80 != 0
	return v
}

// writeG10V2 encodes g10v2, BinaryOutputWithFlags.
func writeG10V2(dst []byte, v dnp3.BinaryOutputStatus, ctx Context) []byte {
	_ = ctx
	flags := v.Flags &^ dnp3.StateBit
	if v.Value {
		flags |= dnp3.StateBit
	}
	dst = append(dst, byte(flags))
	return dst
}

// parseG11V1 decodes g11v1, BinaryOutputEventNoTime.
func parseG11V1(buf []byte, ctx Context) dnp3.BinaryOutputStatus {
	var v dnp3.BinaryOutputStatus
	_ = buf[0] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = buf[0]&0x80 != 0
	return v
}

// writeG11V1 encodes g11v1, BinaryOutputEventNoTime.
func writeG11V1(dst []byte, v dnp3.BinaryOutputStatus, ctx Context) []byte {
	_ = ctx
	flags := v.Flags &^ dnp3.StateBit
	if v.Value {
		flags |= dnp3.StateBit
	}
	dst = append(dst, byte(flags))
	return dst
}

// parseG11V2 decodes g11v2, BinaryOutputEventAbsTime.
func parseG11V2(buf []byte, ctx Context) dnp3.BinaryOutputStatus {
	var v dnp3.BinaryOutputStatus
	_ = buf[6] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = buf[0]&0x80 != 0
	v.Time = dnp3.Timestamp{Time: dnp3.DNP3ToTime(uint64(buf[1])<<0 | uint64(buf[2])<<8 | uint64(buf[3])<<16 | uint64(buf[4])<<24 | uint64(buf[5])<<32 | uint64(buf[6])<<40), Quality: ctx.TimeQuality()}
	return v
}

// writeG11V2 encodes g11v2, BinaryOutputEventAbsTime.
func writeG11V2(dst []byte, v dnp3.BinaryOutputStatus, ctx Context) []byte {
	_ = ctx
	flags := v.Flags &^ dnp3.StateBit
	if v.Value {
		flags |= dnp3.StateBit
	}
	dst = append(dst, byte(flags))
	dst = appendTime48(dst, dnp3.TimeToDNP3(v.Time.Time))
	return dst
}

var binaryoutputCodecs = map[GroupVar]Codec[dnp3.BinaryOutputStatus]{
	GV(10, 2): {Parse: parseG10V2, Write: writeG10V2},
	GV(11, 1): {Parse: parseG11V1, Write: writeG11V1},
	GV(11, 2): {Parse: parseG11V2, Write: writeG11V2},
}

// ---- dnp3.AnalogOutputStatus ----

// parseG40V1 decodes g40v1, AnalogOutputStatus32.
func parseG40V1(buf []byte, ctx Context) dnp3.AnalogOutputStatus {
	var v dnp3.AnalogOutputStatus
	_ = buf[4] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = float64(int32(binary.LittleEndian.Uint32(buf[1:5])))
	return v
}

// writeG40V1 encodes g40v1, AnalogOutputStatus32.
func writeG40V1(dst []byte, v dnp3.AnalogOutputStatus, ctx Context) []byte {
	_ = ctx
	dst = append(dst, byte(v.Flags))
	dst = binary.LittleEndian.AppendUint32(dst, uint32(clampInt32(v.Value)))
	return dst
}

// parseG40V2 decodes g40v2, AnalogOutputStatus16.
func parseG40V2(buf []byte, ctx Context) dnp3.AnalogOutputStatus {
	var v dnp3.AnalogOutputStatus
	_ = buf[2] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = float64(int16(binary.LittleEndian.Uint16(buf[1:3])))
	return v
}

// writeG40V2 encodes g40v2, AnalogOutputStatus16.
func writeG40V2(dst []byte, v dnp3.AnalogOutputStatus, ctx Context) []byte {
	_ = ctx
	dst = append(dst, byte(v.Flags))
	dst = binary.LittleEndian.AppendUint16(dst, uint16(clampInt16(v.Value)))
	return dst
}

// parseG40V3 decodes g40v3, AnalogOutputStatusFloat.
func parseG40V3(buf []byte, ctx Context) dnp3.AnalogOutputStatus {
	var v dnp3.AnalogOutputStatus
	_ = buf[4] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = float64(math.Float32frombits(binary.LittleEndian.Uint32(buf[1:5])))
	return v
}

// writeG40V3 encodes g40v3, AnalogOutputStatusFloat.
func writeG40V3(dst []byte, v dnp3.AnalogOutputStatus, ctx Context) []byte {
	_ = ctx
	dst = append(dst, byte(v.Flags))
	dst = binary.LittleEndian.AppendUint32(dst, math.Float32bits(float32(v.Value)))
	return dst
}

// parseG40V4 decodes g40v4, AnalogOutputStatusDouble.
func parseG40V4(buf []byte, ctx Context) dnp3.AnalogOutputStatus {
	var v dnp3.AnalogOutputStatus
	_ = buf[8] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = math.Float64frombits(binary.LittleEndian.Uint64(buf[1:9]))
	return v
}

// writeG40V4 encodes g40v4, AnalogOutputStatusDouble.
func writeG40V4(dst []byte, v dnp3.AnalogOutputStatus, ctx Context) []byte {
	_ = ctx
	dst = append(dst, byte(v.Flags))
	dst = binary.LittleEndian.AppendUint64(dst, math.Float64bits(v.Value))
	return dst
}

// parseG42V1 decodes g42v1, AnalogOutputEvent32.
func parseG42V1(buf []byte, ctx Context) dnp3.AnalogOutputStatus {
	var v dnp3.AnalogOutputStatus
	_ = buf[4] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = float64(int32(binary.LittleEndian.Uint32(buf[1:5])))
	return v
}

// writeG42V1 encodes g42v1, AnalogOutputEvent32.
func writeG42V1(dst []byte, v dnp3.AnalogOutputStatus, ctx Context) []byte {
	_ = ctx
	dst = append(dst, byte(v.Flags))
	dst = binary.LittleEndian.AppendUint32(dst, uint32(clampInt32(v.Value)))
	return dst
}

// parseG42V2 decodes g42v2, AnalogOutputEvent16.
func parseG42V2(buf []byte, ctx Context) dnp3.AnalogOutputStatus {
	var v dnp3.AnalogOutputStatus
	_ = buf[2] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = float64(int16(binary.LittleEndian.Uint16(buf[1:3])))
	return v
}

// writeG42V2 encodes g42v2, AnalogOutputEvent16.
func writeG42V2(dst []byte, v dnp3.AnalogOutputStatus, ctx Context) []byte {
	_ = ctx
	dst = append(dst, byte(v.Flags))
	dst = binary.LittleEndian.AppendUint16(dst, uint16(clampInt16(v.Value)))
	return dst
}

// parseG42V3 decodes g42v3, AnalogOutputEvent32Time.
func parseG42V3(buf []byte, ctx Context) dnp3.AnalogOutputStatus {
	var v dnp3.AnalogOutputStatus
	_ = buf[10] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = float64(int32(binary.LittleEndian.Uint32(buf[1:5])))
	v.Time = dnp3.Timestamp{Time: dnp3.DNP3ToTime(uint64(buf[5])<<0 | uint64(buf[6])<<8 | uint64(buf[7])<<16 | uint64(buf[8])<<24 | uint64(buf[9])<<32 | uint64(buf[10])<<40), Quality: ctx.TimeQuality()}
	return v
}

// writeG42V3 encodes g42v3, AnalogOutputEvent32Time.
func writeG42V3(dst []byte, v dnp3.AnalogOutputStatus, ctx Context) []byte {
	_ = ctx
	dst = append(dst, byte(v.Flags))
	dst = binary.LittleEndian.AppendUint32(dst, uint32(clampInt32(v.Value)))
	dst = appendTime48(dst, dnp3.TimeToDNP3(v.Time.Time))
	return dst
}

// parseG42V4 decodes g42v4, AnalogOutputEvent16Time.
func parseG42V4(buf []byte, ctx Context) dnp3.AnalogOutputStatus {
	var v dnp3.AnalogOutputStatus
	_ = buf[8] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = float64(int16(binary.LittleEndian.Uint16(buf[1:3])))
	v.Time = dnp3.Timestamp{Time: dnp3.DNP3ToTime(uint64(buf[3])<<0 | uint64(buf[4])<<8 | uint64(buf[5])<<16 | uint64(buf[6])<<24 | uint64(buf[7])<<32 | uint64(buf[8])<<40), Quality: ctx.TimeQuality()}
	return v
}

// writeG42V4 encodes g42v4, AnalogOutputEvent16Time.
func writeG42V4(dst []byte, v dnp3.AnalogOutputStatus, ctx Context) []byte {
	_ = ctx
	dst = append(dst, byte(v.Flags))
	dst = binary.LittleEndian.AppendUint16(dst, uint16(clampInt16(v.Value)))
	dst = appendTime48(dst, dnp3.TimeToDNP3(v.Time.Time))
	return dst
}

// parseG42V5 decodes g42v5, AnalogOutputEventFloat.
func parseG42V5(buf []byte, ctx Context) dnp3.AnalogOutputStatus {
	var v dnp3.AnalogOutputStatus
	_ = buf[4] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = float64(math.Float32frombits(binary.LittleEndian.Uint32(buf[1:5])))
	return v
}

// writeG42V5 encodes g42v5, AnalogOutputEventFloat.
func writeG42V5(dst []byte, v dnp3.AnalogOutputStatus, ctx Context) []byte {
	_ = ctx
	dst = append(dst, byte(v.Flags))
	dst = binary.LittleEndian.AppendUint32(dst, math.Float32bits(float32(v.Value)))
	return dst
}

// parseG42V6 decodes g42v6, AnalogOutputEventDouble.
func parseG42V6(buf []byte, ctx Context) dnp3.AnalogOutputStatus {
	var v dnp3.AnalogOutputStatus
	_ = buf[8] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = math.Float64frombits(binary.LittleEndian.Uint64(buf[1:9]))
	return v
}

// writeG42V6 encodes g42v6, AnalogOutputEventDouble.
func writeG42V6(dst []byte, v dnp3.AnalogOutputStatus, ctx Context) []byte {
	_ = ctx
	dst = append(dst, byte(v.Flags))
	dst = binary.LittleEndian.AppendUint64(dst, math.Float64bits(v.Value))
	return dst
}

// parseG42V7 decodes g42v7, AnalogOutputEventFloatTime.
func parseG42V7(buf []byte, ctx Context) dnp3.AnalogOutputStatus {
	var v dnp3.AnalogOutputStatus
	_ = buf[10] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = float64(math.Float32frombits(binary.LittleEndian.Uint32(buf[1:5])))
	v.Time = dnp3.Timestamp{Time: dnp3.DNP3ToTime(uint64(buf[5])<<0 | uint64(buf[6])<<8 | uint64(buf[7])<<16 | uint64(buf[8])<<24 | uint64(buf[9])<<32 | uint64(buf[10])<<40), Quality: ctx.TimeQuality()}
	return v
}

// writeG42V7 encodes g42v7, AnalogOutputEventFloatTime.
func writeG42V7(dst []byte, v dnp3.AnalogOutputStatus, ctx Context) []byte {
	_ = ctx
	dst = append(dst, byte(v.Flags))
	dst = binary.LittleEndian.AppendUint32(dst, math.Float32bits(float32(v.Value)))
	dst = appendTime48(dst, dnp3.TimeToDNP3(v.Time.Time))
	return dst
}

// parseG42V8 decodes g42v8, AnalogOutputEventDoubleTime.
func parseG42V8(buf []byte, ctx Context) dnp3.AnalogOutputStatus {
	var v dnp3.AnalogOutputStatus
	_ = buf[14] // bounds check once, then index freely
	v.Flags = dnp3.Flags(buf[0])
	v.Value = math.Float64frombits(binary.LittleEndian.Uint64(buf[1:9]))
	v.Time = dnp3.Timestamp{Time: dnp3.DNP3ToTime(uint64(buf[9])<<0 | uint64(buf[10])<<8 | uint64(buf[11])<<16 | uint64(buf[12])<<24 | uint64(buf[13])<<32 | uint64(buf[14])<<40), Quality: ctx.TimeQuality()}
	return v
}

// writeG42V8 encodes g42v8, AnalogOutputEventDoubleTime.
func writeG42V8(dst []byte, v dnp3.AnalogOutputStatus, ctx Context) []byte {
	_ = ctx
	dst = append(dst, byte(v.Flags))
	dst = binary.LittleEndian.AppendUint64(dst, math.Float64bits(v.Value))
	dst = appendTime48(dst, dnp3.TimeToDNP3(v.Time.Time))
	return dst
}

var analogoutputCodecs = map[GroupVar]Codec[dnp3.AnalogOutputStatus]{
	GV(40, 1): {Parse: parseG40V1, Write: writeG40V1},
	GV(40, 2): {Parse: parseG40V2, Write: writeG40V2},
	GV(40, 3): {Parse: parseG40V3, Write: writeG40V3},
	GV(40, 4): {Parse: parseG40V4, Write: writeG40V4},
	GV(42, 1): {Parse: parseG42V1, Write: writeG42V1},
	GV(42, 2): {Parse: parseG42V2, Write: writeG42V2},
	GV(42, 3): {Parse: parseG42V3, Write: writeG42V3},
	GV(42, 4): {Parse: parseG42V4, Write: writeG42V4},
	GV(42, 5): {Parse: parseG42V5, Write: writeG42V5},
	GV(42, 6): {Parse: parseG42V6, Write: writeG42V6},
	GV(42, 7): {Parse: parseG42V7, Write: writeG42V7},
	GV(42, 8): {Parse: parseG42V8, Write: writeG42V8},
}
