// Code generated by internal/gen from objects/spec/dnp3_objects.yaml. DO NOT EDIT.

package app

// generatedSizes maps a group and variation to the encoded size of one
// object in bits. Sizes under eight bits are bit-packed across a range.
var generatedSizes = map[uint16]int{
	gv(1, 1):   1,   // BinaryInputPacked
	gv(1, 2):   8,   // BinaryInputWithFlags
	gv(2, 1):   8,   // BinaryInputEventNoTime
	gv(2, 2):   56,  // BinaryInputEventAbsTime
	gv(2, 3):   24,  // BinaryInputEventRelTime
	gv(3, 1):   2,   // DoubleBitInputPacked
	gv(3, 2):   8,   // DoubleBitInputWithFlags
	gv(4, 1):   8,   // DoubleBitEventNoTime
	gv(4, 2):   56,  // DoubleBitEventAbsTime
	gv(4, 3):   24,  // DoubleBitEventRelTime
	gv(10, 1):  1,   // BinaryOutputPacked
	gv(10, 2):  8,   // BinaryOutputWithFlags
	gv(11, 1):  8,   // BinaryOutputEventNoTime
	gv(11, 2):  56,  // BinaryOutputEventAbsTime
	gv(12, 1):  88,  // ControlRelayOutputBlock
	gv(12, 2):  88,  // PatternControlBlock
	gv(12, 3):  1,   // PatternMask
	gv(13, 1):  8,   // BinaryOutputCmdEventNoTime
	gv(13, 2):  56,  // BinaryOutputCmdEventAbsTime
	gv(20, 1):  40,  // Counter32WithFlag
	gv(20, 2):  24,  // Counter16WithFlag
	gv(20, 5):  32,  // Counter32NoFlag
	gv(20, 6):  16,  // Counter16NoFlag
	gv(21, 1):  40,  // FrozenCounter32WithFlag
	gv(21, 2):  24,  // FrozenCounter16WithFlag
	gv(21, 5):  88,  // FrozenCounter32WithFlagTime
	gv(21, 6):  72,  // FrozenCounter16WithFlagTime
	gv(21, 9):  32,  // FrozenCounter32NoFlag
	gv(21, 10): 16,  // FrozenCounter16NoFlag
	gv(22, 1):  40,  // CounterEvent32WithFlag
	gv(22, 2):  24,  // CounterEvent16WithFlag
	gv(22, 5):  88,  // CounterEvent32WithFlagTime
	gv(22, 6):  72,  // CounterEvent16WithFlagTime
	gv(23, 1):  40,  // FrozenCounterEvent32WithFlag
	gv(23, 2):  24,  // FrozenCounterEvent16WithFlag
	gv(23, 5):  88,  // FrozenCounterEvent32WithFlagTime
	gv(23, 6):  72,  // FrozenCounterEvent16WithFlagTime
	gv(30, 1):  40,  // AnalogInput32WithFlag
	gv(30, 2):  24,  // AnalogInput16WithFlag
	gv(30, 3):  32,  // AnalogInput32NoFlag
	gv(30, 4):  16,  // AnalogInput16NoFlag
	gv(30, 5):  40,  // AnalogInputFloatWithFlag
	gv(30, 6):  72,  // AnalogInputDoubleWithFlag
	gv(31, 1):  40,  // FrozenAnalog32WithFlag
	gv(31, 2):  24,  // FrozenAnalog16WithFlag
	gv(31, 3):  88,  // FrozenAnalog32WithFlagTime
	gv(31, 4):  72,  // FrozenAnalog16WithFlagTime
	gv(31, 5):  32,  // FrozenAnalog32NoFlag
	gv(31, 6):  16,  // FrozenAnalog16NoFlag
	gv(31, 7):  40,  // FrozenAnalogFloatWithFlag
	gv(31, 8):  72,  // FrozenAnalogDoubleWithFlag
	gv(32, 1):  40,  // AnalogEvent32WithFlag
	gv(32, 2):  24,  // AnalogEvent16WithFlag
	gv(32, 3):  88,  // AnalogEvent32WithFlagTime
	gv(32, 4):  72,  // AnalogEvent16WithFlagTime
	gv(32, 5):  40,  // AnalogEventFloatWithFlag
	gv(32, 6):  72,  // AnalogEventDoubleWithFlag
	gv(32, 7):  88,  // AnalogEventFloatWithFlagTime
	gv(32, 8):  120, // AnalogEventDoubleWithFlagTime
	gv(33, 1):  40,  // FrozenAnalogEvent32WithFlag
	gv(33, 2):  24,  // FrozenAnalogEvent16WithFlag
	gv(33, 3):  88,  // FrozenAnalogEvent32WithFlagTime
	gv(33, 4):  72,  // FrozenAnalogEvent16WithFlagTime
	gv(33, 5):  40,  // FrozenAnalogEventFloatWithFlag
	gv(33, 6):  72,  // FrozenAnalogEventDoubleWithFlag
	gv(33, 7):  88,  // FrozenAnalogEventFloatWithFlagTime
	gv(33, 8):  120, // FrozenAnalogEventDoubleWithFlagTime
	gv(34, 1):  16,  // AnalogDeadband16
	gv(34, 2):  32,  // AnalogDeadband32
	gv(34, 3):  32,  // AnalogDeadbandFloat
	gv(40, 1):  40,  // AnalogOutputStatus32
	gv(40, 2):  24,  // AnalogOutputStatus16
	gv(40, 3):  40,  // AnalogOutputStatusFloat
	gv(40, 4):  72,  // AnalogOutputStatusDouble
	gv(41, 1):  40,  // AnalogOutput32
	gv(41, 2):  24,  // AnalogOutput16
	gv(41, 3):  40,  // AnalogOutputFloat
	gv(41, 4):  72,  // AnalogOutputDouble
	gv(42, 1):  40,  // AnalogOutputEvent32
	gv(42, 2):  24,  // AnalogOutputEvent16
	gv(42, 3):  88,  // AnalogOutputEvent32Time
	gv(42, 4):  72,  // AnalogOutputEvent16Time
	gv(42, 5):  40,  // AnalogOutputEventFloat
	gv(42, 6):  72,  // AnalogOutputEventDouble
	gv(42, 7):  88,  // AnalogOutputEventFloatTime
	gv(42, 8):  120, // AnalogOutputEventDoubleTime
	gv(43, 1):  40,  // AnalogOutputCmdEvent32
	gv(43, 2):  24,  // AnalogOutputCmdEvent16
	gv(43, 3):  88,  // AnalogOutputCmdEvent32Time
	gv(43, 4):  72,  // AnalogOutputCmdEvent16Time
	gv(43, 5):  40,  // AnalogOutputCmdEventFloat
	gv(43, 6):  72,  // AnalogOutputCmdEventDouble
	gv(43, 7):  88,  // AnalogOutputCmdEventFloatTime
	gv(43, 8):  120, // AnalogOutputCmdEventDoubleTime
	gv(50, 1):  48,  // TimeAndDate
	gv(50, 2):  80,  // TimeAndDateInterval
	gv(50, 3):  48,  // TimeAndDateLastRecorded
	gv(50, 4):  88,  // TimeAndDateIndexed
	gv(51, 1):  48,  // TimeAndDateCTO
	gv(51, 2):  48,  // UnsyncTimeAndDateCTO
	gv(52, 1):  16,  // TimeDelayCoarse
	gv(52, 2):  16,  // TimeDelayFine
	gv(60, 1):  0,   // Class0Data
	gv(60, 2):  0,   // Class1Data
	gv(60, 3):  0,   // Class2Data
	gv(60, 4):  0,   // Class3Data
	gv(80, 1):  1,   // InternalIndications
}

// lengthIsVariationGroups carry their octet length in the variation number.
var lengthIsVariationGroups = map[uint8]bool{
	110: true, // OctetString
	111: true, // OctetStringEvent
	112: true, // VirtualTerminalOutput
	113: true, // VirtualTerminalEvent
}

// variableGroups have no fixed size; their encoding carries one.
var variableGroups = map[uint8]bool{
	0:  true, // DeviceAttribute
	70: true, // FileTransfer
}
